### ISSUE TITLE
Any specification for firmware binary?

### ISSUE THREAD

**Issue by natekfl** [ap51-flash/ap51-flash#16]
I apologize in advance if this is is a stupid question, I'm still learning :)

Is there any specification on how the firmware files are parsed, and then the files needed to be served over TFTP are extracted? I am looking at the fwcfg.c file and I am understanding bits and pieces of what's going on, but is there any formal specification or documentation as to how the firmware files are laid out?

**Comment by ecsv** [comment]
The fwcfg.c is not about an image format but the flash configuration file for OpenMesh, Datto and Plasmacloud devices. Their u-boot is repsonsible for interpreting them.

But this fwupgrade.cfg is usually part of the combined extended image format v1 from OpenWrt: https://github.com/openwrt/openwrt/blob/master/scripts/combined-ext-image.sh

Afaik, there is no more information available at the moment.

**Comment by natekfl** [comment]
Thank you so much! My lack of understanding about all of this led me to believe that the CE header and the key value pairs of fwupgrade.cfg were all one in the same, hence why I thought that file was relevant. Thank you for clarifying!
