### ISSUE TITLE
Not work on MR600

### ISSUE THREAD

**Issue by crashcoq** [ap51-flash/ap51-flash#20]
Hello

I can't use this soft for update my MR600 V2
![16570427155334915927664061474619](https://user-images.githubusercontent.com/8464834/177530819-78f7ad1d-ec12-4e0f-bcba-eab7141cb05c.jpg)

Any response with or without Mac router?
I have reboot and hold 5 seconds the wps button,  same problem. 

Could you help me?

Cordially

**Comment by ecsv** [comment]
Wrong file. You must use the [openmesh_mr600-v2-squashfs-sysupgrade.bin](https://downloads.openwrt.org/releases/21.02.3/targets/ath79/generic/openwrt-21.02.3-ath79-generic-openmesh_mr600-v2-squashfs-sysupgrade.bin)

**Comment by crashcoq** [comment]
I have tested with the file
Same problem 
My router don't appear on ap51 terminal, but I view other Mac on Lan.
I use only ethernet.
