### ISSUE TITLE
OM2P that we have no image for

### ISSUE THREAD

**Issue by brynnneilson** [ap51-flash/ap51-flash#22]
I'm trying to flash my OM2P-HS V2 router with: 
./ap51-flash enp3s0 openwrt-22.03.2-ath79-generic-openmesh_om2p-hs-v2-initramfs-kernel.bin

But after it finds the OM2P-HS it says:
is of type 'OM2P' that we have no image for

Any suggestions?

**Comment by brynnneilson** [comment]
All it said was "[router mac address] is of type 'OM2P' that we have no image for". 

When I ran the original "./open-mesh-flash-ng enp3s0", that has the proprietary firmware file embeded, it says the router's name is "OM2P Router" not "OM2P"

open-mesh-flash-ng is just thier version of ap51-flash with their firmware embeded in open-mesh-flash-ng but you can also specify an external firmware file. When I do that it comes back with the same error.

**Comment by lindnermarek** [comment]
Please keep in mind that you are interacting with a bug tracker - not a support platform.

The message "is of type 'OM2P' that we have no image for" means what it says: You are not providing the right firmware image to flash the OM2P with.

If the word "router" confuses you, please check the following commit: https://github.com/ap51-flash/ap51-flash/commit/90abcb8d250c21bff44d288aec30b35e8bf6543b

**Comment by brynnneilson** [comment]
Oh. Thanks. That gives me something to work on. Thanks for your time.

**Comment by ecsv** [comment]
> I'm trying to flash my OM2P-HS V2 router with: ./ap51-flash enp3s0 openwrt-22.03.2-ath79-generic-openmesh_om2p-hs-v2-initramfs-kernel.bin

If you want to flash OpenWrt 22.03.2 on the OM2P-HS then you have to provide a flashable image. These are usually called "factory" images in OpenWrt. But for the ath79 target, OpenWrt uses a sysupgrade image for both factory installation and sysupgrades. An initramfs image is for manually loading the file via u-boot into RAM and then manually executing this the code from the RAM region (so it is more like a "livecd" for routers).

See https://github.com/openwrt/openwrt/commit/f096accce26bc46831e859ccd40b3f88e404cc7e for more info.

https://downloads.openwrt.org/releases/22.03.2/targets/ath79/generic/openwrt-22.03.2-ath79-generic-openmesh_om2p-hs-v2-squashfs-sysupgrade.bin

**Comment by brynnneilson** [comment]
Thank you so much. That really helps. I purchased these units second-hand to setup free wifi in my village during Covid but now the Cloudtrax portal doesn't allow me to add any new devices, because they are end-of-life, so I'm looking to migrate the system to Open Source: https://www.sanson.net.nz/sanson-free-wifi
