### ISSUE TITLE
Unsupported Image

### ISSUE THREAD

**Issue by ClausBam** [ap51-flash/ap51-flash#23]
Hi there. I just tried to flash V517ABPC1C0.bin to my Zyxel 7051 router which is an official Zyxel Firmware. I got the error message: 

.\ap51-flash-2022.0-i686-npcap 8 V517ABPC1C0.bin
Unsupported image 'V517ABPC1C0.bin': ignoring file
Error - no images specified

I tried it both in the Linux Terminal and in Powershell which both resultet in the same message.

Could you please specify which Firmware images are supported and if there may be a way to make this firmware compatible? Thanks a lot in advance.

**Comment by lindnermarek** [comment]
You can find the Zyxel image check here: https://github.com/ap51-flash/ap51-flash/blob/main/router_images.c#L450

This check / identification was based on the Zyxel router available to me at that time (model: NBG6617).

The image you are trying to flash may be different. You'd have to dive into the specifics of how the present image is constructed and how it is supposed to be unpacked & flashed.
