### ISSUE TITLE
Type 'OM5P-AC' has no image

### ISSUE THREAD

**Issue by WaterGame2023** [ap51-flash/ap51-flash#25]
I am trying to flash OpenWRT to an OpenMesh OM5P-AC V2, which is listed as supported by ap51, but when I try to flash the AP using the command `./ap51-flash-2022.1-x86_64-linux enp1s0 openwrt-22.03.3-ath79-generic-openmesh_om5p-ac-v2-initramfs-kernel.bin` I get `[f8:d9:b8:07:6c:00]: is of type 'OM5P-AC' that we have no image for.`  Am I doing something wrong? If so what is the fix?

**Comment by ecsv** [comment]
The initramfs is nothing which you can flash. You can use it to manually start into system only running in ram.

Please use https://downloads.openwrt.org/releases/22.03.3/targets/ath79/generic/openwrt-22.03.3-ath79-generic-openmesh_om5p-ac-v2-squashfs-sysupgrade.bin
